### ISSUE TITLE
Type 201 / 202

### ISSUE THREAD

**Issue by denysvitali** [denysvitali/ca-combos-editor#2]
Today I received the following email:
> Добрый день , мы тут всем форумом 4pda бьемся , что бы создать файл агрегаций на note10 snapdragon . Файл  агрегаций для  s10 snapdragon у нас есть и он уже переделан под наших операторов, но если его поставить на  note 10  то пропадает сеть , видимо где-то есть загвоздка , к сожалению моих знаний не хватает  на редактирование этого файла , если есть возможно поправить  файл с s10 под note 10 было бы отлично .

Which translates to:
> Good afternoon, we're all over the 4pda forum fighting to create an aggregation file on note10 snapdragon. 
We have the aggregation file for s10 snapdragon and it is already rebuilt for our operators, but if you put it on note 10 then the network disappears, probably somewhere there is a hurdle, unfortunately my knowledge is not enough to edit this file, if there is a possibility to fix the file with s10 to note 10 would be great.  
  
Attachment: [00028874.zip](https://github.com/denysvitali/ca-combos-editor/files/4247173/00028874.zip)

This issue covers the resolution and parsing of this new type (201 and 202)

**Comment by denysvitali** [comment]
![image](https://user-images.githubusercontent.com/4939519/69677485-5d584100-10a3-11ea-8ea3-60ab97da4bf2.png)

Band = Green  
Class (A = 1, B = 2, C = 3) = Orange  
MIMO = Purple

**Comment by denysvitali** [comment]
![image](https://user-images.githubusercontent.com/4939519/69677485-5d584100-10a3-11ea-8ea3-60ab97da4bf2.png)

Band = Green  
Class (A = 1, B = 2, C = 3) = Orange  
MIMO = Purple  
  
201 = Downlink  
202 = Uplink

**Comment by jarny-auyang** [comment]
me also got this issue , how to fix pls?

#go run cmd/main.go create bands.txt 00028774_uncompressed
DEBU[0000] comboString: 1A4A-1A4                        
DEBU[0000] => [1A-1A 1A]                                
DEBU[0000] comboString: 1A4A-3A4                        
DEBU[0000] => [3A-1A 1A]                                
DEBU[0000] comboString: 1A4A-8A4                        
DEBU[0000] => [8A-1A 1A]

**Comment by denysvitali** [comment]
@jarny-auyang , yours seems to be another issue: in your case the MIMO capabilities are not parsed correctly (everything gets converted to a 2x2).  
  
Please open another issue, I'm going to close this one since it is fixed
