### ISSUE TITLE
New 00028874 file does not work

### ISSUE THREAD

**Issue by jason-akw** [denysvitali/ca-combos-editor#3]
Hi,

I'm trying to use this tool to make new 00028874 file,
but it seems zlib-flate does not support compression level set,
I only can use `zlib-flate -compress < $1 > 00028874` instead of `zlib-flate -compress=6 < $1 > 00028874` on your script.

But it seems the output file does not work, the modem shows an error.
Then I tried to use 28874Decoder (https://github.com/HandyMenny/28874Decoder) to decode the new file,
the program returns many error messages.

```
Incorrect format: incorrect descriptor type 6515 (137, 138, 201, 202, 333 or 334 expected). File offset=4.
Incorrect format: incorrect descriptor type 24030 (137, 138, 201, 202, 333 or 334 expected). File offset=6.
Incorrect format: incorrect descriptor type 768 (137, 138, 201, 202, 333 or 334 expected). File offset=8.
Incorrect format: incorrect descriptor type 22189 (137, 138, 201, 202, 333 or 334 expected). File offset=a.
Incorrect format: incorrect descriptor type 3649 (137, 138, 201, 202, 333 or 334 expected). File offset=c.
Incorrect format: incorrect descriptor type 12419 (137, 138, 201, 202, 333 or 334 expected). File offset=e.
Incorrect format: incorrect descriptor type 19212 (137, 138, 201, 202, 333 or 334 expected). File offset=10.
Incorrect format: incorrect descriptor type 41417 (137, 138, 201, 202, 333 or 334 expected). File offset=12.
Incorrect format: incorrect descriptor type 32828 (137, 138, 201, 202, 333 or 334 expected). File offset=14.
Incorrect format: incorrect descriptor type 34595 (137, 138, 201, 202, 333 or 334 expected). File offset=16.
Incorrect format: incorrect descriptor type 4253 (137, 138, 201, 202, 333 or 334 expected). File offset=18.
Incorrect format: incorrect descriptor type 25951 (137, 138, 201, 202, 333 or 334 expected). File offset=1a.
Incorrect format: incorrect descriptor type 55743 (137, 138, 201, 202, 333 or 334 expected). File offset=1c.
```

It seems there is something wrong on the new file.

**Comment by denysvitali** [comment]
The `parse` subcommand expects an uncompressed 00028874 file (use `./uncompress.sh`)

**Comment by jason-akw** [comment]
Oh sorry, I forget this.

Now I have a new question.
I'm testing it using these commands:
 
```
echo "3A2-3A2-7A4A" > band.txt
go run cmd/main.go create band.txt 00028874_uncompressed
```
Output:
> DEBU[0000] comboString: 3A2-3A2-7A4A                    
> DEBU[0000] => [7A-3A-3A 7A]                             
> INFO[0000] Writing 2 entries...                 

I got "3A2-3A2-7A2A" on 00028874_uncompressed file,
Seems the program converted all 4x4 combo to 2x2.

**Comment by denysvitali** [comment]
According to the format specification that I've got (self taught to be honest) , a 4x4 combo should be represented as 3A4-7A4. I may be wrong though.  
  
Example: https://cacombos.com/device?model=GM1920

**Comment by Medvedgod** [comment]
Привет. Я сделал 2 скрипта для работы под виндой, чтобы не использовать zlib. Вечером выложу.

**Comment by denysvitali** [comment]
> Привет. Я сделал 2 скрипта для работы под виндой, чтобы не использовать zlib. Вечером выложу.
> Hi. I made 2 scripts to work under windows to avoid using zlib. In the evening I will put it out.

Thank you!

**Comment by jason-akw** [comment]
> According to the format specification that I've got (self taught to be honest) , a 4x4 combo should be represented as 3A4-7A4. I may be wrong though.
> 
> Example: https://cacombos.com/device?model=GM1920

I got the format from cacombos.com also, like this: https://cacombos.com/device?model=OnePlus7TProEU

![image](https://user-images.githubusercontent.com/8659165/69717706-83cfb800-1147-11ea-913a-490da64da4a8.png)

I tried "3A4-7A4", then I got:
```
DEBU[0000] comboString: 3A4-7A4                         
DEBU[0000] => [7A-3A ]                                  
INFO[0000] Writing 2 entries... 
```
The program has converted to 3A2-7A2 instead of 3A4-7A4.

**Comment by denysvitali** [comment]
Maybe it should be something like this?
```
3A4-3A4A-7A4-7A4
```

becomes:
```
time="2019-11-27T12:33:56+01:00" level=debug msg="=> [7A-7A-3A-3A 3A]"
```

**Comment by jason-akw** [comment]
```
# echo "3A4-3A4A-7A4-7A4" > band.txt
# go run cmd/main.go create band.txt 00028774_uncompressed
DEBU[0000] comboString: 3A4-3A4A-7A4-7A4                
DEBU[0000] => [7A-7A-3A-3A 3A]                          
INFO[0000] Writing 2 entries...                         

# ../28874Decoder/src/28874Decoder 00028774_uncompressed 
Input file size: 44 bytes
Format verson: 0
Number of descriptors: 2

3A2A-3A2-7A2-7A2 8 

```

Umm... It still converted to B3+B3+B7+B7 with 2x2 MIMO for all.

**Comment by denysvitali** [comment]
Oh, I understand your problem now. The entry type 137 / 138 doesn't support MIMO. We probably have to write a 201 / 202 entry (#2) for that 😄

**Comment by Medvedgod** [comment]
Не могу понять, почему 00028874 от S10 не подходит к N10? Процессор и модем один и тот же.

**Comment by denysvitali** [comment]
@Medvedgod You should probably edit the `carrier_policy.xml` too

**Comment by Medvedgod** [comment]
Можете выложить файлы из policyman/

У нас состав файл:
[carrier_policy.txt](https://github.com/denysvitali/ca-combos-editor/files/3902985/carrier_policy.txt)
[post.txt](https://github.com/denysvitali/ca-combos-editor/files/3902998/post.txt)
[device_config.txt](https://github.com/denysvitali/ca-combos-editor/files/3902999/device_config.txt)

**Comment by denysvitali** [comment]
Tracking the 4x4 MIMO issue in #6

**Comment by denysvitali** [comment]
I'm closing this issue, feel free to re-open it if you feel it is still not solved
