### ISSUE TITLE
Rmt storage path doesn't work

### ISSUE THREAD

**Issue by Bastel2020** [denysvitali/ca-combos-editor#4]
I tried to apply rmt storage path for my OP5T (OOS 9.0.9) but modem does not start with this file; MD5 in instruction and in file have differences.

**Comment by denysvitali** [comment]
Can you try with this one?
[rmt.tar.gz](https://github.com/denysvitali/ca-combos-editor/files/3902732/rmt.tar.gz)

**Comment by Bastel2020** [comment]
does not work.

**Comment by denysvitali** [comment]
What does `dmesg | grep failure` say?  
  
What do you mean by "does not work"? You may need to `restorecon /vendor/bin/rmt_storage` and `pkill rmt_storage && /vendor/bin/rmt_storage` or reboot your phone 💪

**Comment by Bastel2020** [comment]
dmeg says:
`modem subsystem failure reason: (unknown, smem_get_entry_no_rlock failed)`
I rewrited original file to file in repository and reboot phone. After this modem can't start.
After `/vendor/bin/rmt_storage` modem started. But after each reboot I need to do this again.

**Comment by denysvitali** [comment]
What's the output of `ls -laZ /vendor/bin/rmt_storage`?

**Comment by Bastel2020** [comment]
no answer

**Comment by denysvitali** [comment]
You are either not running the command as `root`, missing the capitalization of the `Z` or missing busybox (maybe?).  
  
A proper output should be the following:
![Screenshot_20191128-195240__01](https://user-images.githubusercontent.com/4939519/69827735-ee9cf400-1218-11ea-8807-95d7a22bf77f.jpg)

**Comment by Bastel2020** [comment]
![image](https://user-images.githubusercontent.com/56816172/69829428-ba89f900-1241-11ea-93e2-1fc22ae04625.png)
I got this. Problems in attributes?

**Comment by denysvitali** [comment]
`mount -o remount,rw /vendor && restorecon /vendor/bin/rmt_storage`

**Comment by Bastel2020** [comment]
I change atributes to your, problem fixed.

**Comment by denysvitali** [comment]
I'm glad you fixed the issue 🎉  
  
Feel free to ask any other question by opening an issue if you have any doubt

**Comment by Bastel2020** [comment]
Thank you!
