### ISSUE TITLE
4x4 MIMO not parsed correctly

### ISSUE THREAD

**Issue by jarny-auyang** [denysvitali/ca-combos-editor#6]
Hi, Denys
I'm trying to use this tool to make new 00028874 file,
Seems the program converted all 4x4 combo to 2x2

# go run cmd/main.go create bands.txt 00028874_uncompressed
DEBU[0000] comboString: 1A4A-1A4                        
DEBU[0000] => [1A-1A 1A]                                
DEBU[0000] comboString: 1A4A-3A4                        
DEBU[0000] => [3A-1A 1A]                                
DEBU[0000] comboString: 1A4A-8A4                        
DEBU[0000] => [8A-1A 1A]                                
DEBU[0000] comboString: 3A4A-3A4                        
DEBU[0000] => [3A-3A 3A]                                
DEBU[0000] comboString: 3A4A-8A4                        
DEBU[0000] => [8A-3A 3A]                                
DEBU[0000] comboString: 8A4A-8A4                        
DEBU[0000] => [8A-8A 8A]                                
DEBU[0000] comboString: 41A4A-41A4                      
DEBU[0000] => [41A-41A 41A]                             
INFO[0000] Writing 14 entries...       

# ./src/28874Decoder 00028874_uncompressed
Input file size: 284 bytes
Format verson: 0
Number of descriptors: 14
1A2A-1A2 4 
1A2A-3A2 4 
1A2A-8A2 4 
3A2A-3A2 4 
3A2A-8A2 4 
8A2A-8A2 4 
41A2A-41A2 4 

Number of combos: 7
Max streams per combo: 4

Another thing is that it seems zlib-flate does not support compression level set,
I only can use "zlib-flate -compress < 00028874_uncompressed > 00028874" instead of "zlib-flate -compress=6 < $1 > 00028874" on your script.

**Comment by denysvitali** [comment]
Hello @jarny-auyang ,

thank you for opening this issue: I can confirm this bug. I'll fix the issue ASAP.  
  
What OS are you using for the zlib-deflate utility? What version of zlib are you using?

**Comment by jarny-auyang** [comment]
Linux version 4.15.0-65-generic   ubuntu 18.04.1
zlib Version: 1.2.11

**Comment by denysvitali** [comment]
```
$ pacman -Q zlib 
zlib 1:1.2.11-4
```

```
Usage: zlib-flate { -uncompress | -compress[=n] }
If n is specified with -compress, it is a zlib compression level from
1 to 9 where lower numbers are faster and less compressed and higher
numbers are slower and more compressed
````

```
./compress.sh 00028774_uncompressed && echo $!
0
```

**Comment by denysvitali** [comment]
```
go run cmd/main.go create -h
Usage: main create [--mode MODE] INPUT OUTPUT

Positional arguments:
  INPUT                  Input file
  OUTPUT                 Output file

Options:
  --mode MODE, -m MODE   Mode to use: 137 or 201 [default: 137]
  --help, -h             display this help and exit
```

You're now able to create a 00028874 file w/ 201 / 202 entries by running the following:
```
ca-combos-editor create -m 201 test/resources/2020-02-25/bands.txt 00028874_uncompressed
```  
   
I'm going to close this issue, feel free to comment and re-open the issue if this feature doesn't work as you expect.  
  
Have a wonderful day
